# -*- coding: utf-8 -*-
"""urlshorter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m7NLz2p4fVG4uoroAubd20rVaDApZKzE
"""

import pyshorteners
while True:
  url=input("Please enter the url")

  s=pyshorteners.Shortener()
  print(" Your shortened Url is ->", s.tinyurl.short(url))